[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"

[theme]
base = "dark"
backgroundColor = "#202124"
secondaryBackgroundColor = "#2d2e31"
primaryColor = "#60a5fa"
textColor = "#f0f0f0"
