[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"

[theme]
base = "dark"
backgroundColor = "#3a3b3e"
secondaryBackgroundColor = "#4a4b4e"
primaryColor = "#60a5fa"
textColor = "#f0f0f0"
